name = "Exdices"
uuid = "12445f6d-da47-493b-a91b-e6772a23352d"
version = "0.1.0"
authors = ["Michael Abbott <32575566+mcabbott@users.noreply.github.com>"]

[compat]
OffsetArrays = "1.14.1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"

[targets]
test = ["Test", "OffsetArrays"]
